language: node_js
node_js:
  - "8"
install:
  - npm install
  - npm run build
  - cp -r .ebextensions dist/.ebextensions/
  - cp env/.env.example dist/.env
  - cp .npmrc dist/.npmrc
  - cd dist/ && zip -r dist.zip .
  - ls -a
notifications:
    slack: heftybyte:MfzjodikjxZSS1Vbqyg8inIv
