language: node_js
node_js:
  - "8"
install:
  - npm install
  - npm run build
  - cd dist/ && zip -r dist.zip .
  - ls
deploy:
  - provider: elasticbeanstalk
    access_key_id: ENV["access_key_id"]
    secret_access_key: ENV["secret_access_key"]
    region: "us-west-2"
    app: "Tokens"
    env: "Tokens-env"
    bucket_name: "elasticbeanstalk-us-west-2-606460127508"
    skip_cleanup: true
    zip_file: "dist.zip"
    on:
      branch: travis-deploy
notifications:
    slack: heftybyte:MfzjodikjxZSS1Vbqyg8inIv
